### ISSUE TITLE
порядок імпортів

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/freshcode-node#2]
https://github.com/TarasOstasha/freshcode-node/blob/ff57e49a41f79557686910468426b03e414e9070/controllers/readUserController.js#L1-L4
- прийнято спочатку розташовувати імпорти нативних нодовських модулів, потім модулів з npm, потім локальних, тобто має бути
```javascript
 const fs = require('fs'); 
 const createError = require('http-errors'); 
 const { logUsers } = require('./readFiles'); 
 
const userApiPath = '../api/users.json'; 
```

**Comment by TarasOstasha** [comment]
+
